:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\OpenApiServer
dotnet build src\OpenApiServer
echo Now, run the following to start the project: dotnet run -p src\OpenApiServer\OpenApiServer.csproj --launch-profile web.
echo.
