/* 
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using OpenApiClient.Client;
using OpenApiClient.Api;
using OpenApiClient.Model;

namespace OpenApiClient.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<DefaultApi>(instance);
        }

        
        /// <summary>
        /// Test ProductsGet
        /// </summary>
        [Fact]
        public void ProductsGetTest()
        {
            var response = instance.ProductsGet();
            Assert.IsType<List<Product>> (response);
        }
        
        /// <summary>
        /// Test ProductsPost
        /// </summary>
        [Fact]
        public void ProductsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Product product = null;
            //instance.ProductsPost(product);
            
        }
        
        /// <summary>
        /// Test ProductsProductIdGet
        /// </summary>
        [Fact]
        public void ProductsProductIdGetTest()
        {
            int productId = 1;
            var response = instance.ProductsProductIdGet(productId);
            Assert.IsType<Product>(response);
        }
        
        /// <summary>
        /// Test UsersGet
        /// </summary>
        [Fact]
        public void UsersGetTest()
        {
            var response = instance.UsersGet();
            Assert.IsType<List<User>>(response);
        }

        /// <summary>
        /// Test UsersPost
        /// </summary>
        [Fact]
        public void UsersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //User user = null;
            //instance.UsersPost(user);
            
        }
        
        /// <summary>
        /// Test UsersUserIdGet
        /// </summary>
        [Fact]
        public void UsersUserIdGetTest()
        {
            int userId = 1;
            var response = instance.UsersUserIdGet(userId);
            Assert.IsType<User>(response);
        }
        
    }

}
